### ISSUE TITLE
Midilooper as standalone sends a wierd sync out signal

### ISSUE THREAD

**Issue by Sebizarro** [alexiszbik/midiLoop#2]
Hi, Very nice midi machine, having lots of fun with this!!! Thanks for sharing!
Just encounter a bug or some issue with the sync out.
Sync out works ok with MIDI in clock but using the Midilooper as stand alone it send a weird sync out signal.

**Comment by alexiszbik** [comment]
I will take a look !
I didn't use the standalone clock since long time, cause the looper is always plugged to my MPC.
What version of uCLock are you using?

**Comment by alexiszbik** [comment]
Fix the issue with latest commit.

**Comment by Sebizarro** [comment]
i use the sync out for a drum sequencer/trigger "BIG BUTTON" but the steps or time division is small like1/8.
is there any way to increasing the division from the sync out?
