### ISSUE TITLE
MIDI Clock is not passed through or generated

### ISSUE THREAD

**Issue by jpa73** [alexiszbik/midiLoop#3]
Nice Project.  

The Looper is triggered by Midi Clock from external drum sources, but does not seem to pass that MIDI clock in Thru to the MIDI Out. Is this correct?

Also, when in Start mode with no clock source at the Input, there is no clock generated at the output. Is this also correct behavior?

**Comment by alexiszbik** [comment]
Hi.
If you want to activate MIDI Clock out, you have to change le line 66 of .ino file

put
#define MIDI_CLOCK_THRU 1

instead of 
#define MIDI_CLOCK_THRU 0

Tell me if it fixes your issue.

**Comment by jpa73** [comment]
Ah perfect - thanks.  I'll put in a few comments in code as a reminder and continue with build.
